# Generated by Django 5.0.6 on 2024-06-28 13:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('is_latex', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='option_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Math_Algebra', 'Matemáticas - Álgebra'), ('Math_Statistics', 'Matemáticas - Estadística'), ('Math_Geometry', 'Matemáticas - Geometría'), ('Math_Calculus', 'Matemáticas - Cálculo'), ('Math_Trigonometry', 'Matemáticas - Trigonometría'), ('Math_Probability', 'Matemáticas - Probabilidad'), ('Math_Number Theory', 'Matemáticas - Teoría de Números'), ('Math_Logic', 'Matemáticas - Lógica'), ('Math_Graphics', 'Matemáticas - Gráficos'), ('Math_Tables', 'Matemáticas - Tablas'), ('Physics_Kinematics', 'Física - Cinemática'), ('Physics_Waves', 'Física - Ondas'), ('Physics_Thermodynamics', 'Física - Termodinámica'), ('Physics_Electromagnetism', 'Física - Electromagnetismo'), ('Physics_Optics', 'Física - Óptica'), ('Physics_Mechanics', 'Física - Mecánica'), ('Physics_Acoustics', 'Física - Acústica'), ('Physics_Astronomy', 'Física - Astronomía'), ('Physics_Nuclear Physics', 'Física - Física Nuclear'), ('Physics_Relativity', 'Física - Relatividad'), ('Physics_Particle Physics', 'Física - Física de Partículas'), ('Physics_Dynamics', 'Física - Dinámica'), ('Physics_Energy', 'Física - Energía')], db_index=True, max_length=120)),
                ('difficulty', models.CharField(choices=[('Easy', 'Fácil'), ('Medium', 'Medio'), ('Hard', 'Difícil')], db_index=True, max_length=50)),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('latex_format', models.BooleanField(default=False)),
                ('time_limit', models.DurationField(blank=True, default=datetime.timedelta(seconds=6120), help_text='Tiempo límite para la evaluación (HH:MM:SS)', null=True)),
                ('correct_answer', models.CharField(max_length=200)),
                ('options', models.ManyToManyField(to='evaluations.option')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Matemáticas', max_length=100)),
                ('period', models.CharField(db_index=True, default=1, max_length=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('value_per_question', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('date', models.DateField(db_index=True, default=datetime.datetime.now)),
                ('llm_model', models.CharField(choices=[('ollama', 'Ollama'), ('anthropic', 'Anthropic Claude 3.5')], default='ollama', max_length=10)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluations.course')),
                ('questions', models.ManyToManyField(to='evaluations.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(blank=True, default=list, null=True, verbose_name='Lista de respuestas')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.evaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'student')},
            },
        ),
    ]
