# Generated by Django 5.0.6 on 2024-06-29 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='answer',
            name='feedback_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='time_limit',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=6120), help_text='Tiempo límite para la evaluación (HH:MM:SS)', null=True),
        ),
    ]
