# Generated by Django 5.1.4 on 2025-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Physics', 'Physics'), ('Math_Algebra', 'Math Algebra'), ('EA_MAT_9_2023_1', 'Ea Mat 9 2023 1'), ('EA_MAT_10_2023_1', 'Ea Mat 10 2023 1'), ('Math_Probability', 'Math Probability'), ('Math_Statistics', 'Math Statistics'), ('Math_Geometry', 'Math Geometry'), ('EA_CN_FISICA_10_2023_1y2', 'Ea Cn Fisica 10 2023 1Y2'), ('Math_Number Theory', 'Math Number Theory'), ('EA_MAT_8_2023_1', 'Ea Mat 8 2023 1'), ('Math_Calculus', 'Math Calculus'), ('Math_Trigonometry', 'Math Trigonometry'), ('EA_MAT_7_2023_1', 'Ea Mat 7 2023 1'), ('EA_MAT_11_2023_1', 'Ea Mat 11 2023 1')], db_index=True, max_length=120),
        ),
    ]
