# Generated by Django 5.0.6 on 2024-08-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(choices=[('Math_Algebra', 'Matemáticas - Álgebra'), ('Math_Statistics', 'Matemáticas - Estadística'), ('Math_Geometry', 'Matemáticas - Geometría'), ('Math_Calculus', 'Matemáticas - Cálculo'), ('Math_Trigonometry', 'Matemáticas - Trigonometría'), ('Math_Probability', 'Matemáticas - Probabilidad'), ('Math_Number Theory', 'Matemáticas - Teoría de Números'), ('Math_Logic', 'Matemáticas - Lógica'), ('Math_Graphics', 'Matemáticas - Gráficos'), ('Math_Tables', 'Matemáticas - Tablas'), ('Physics_Kinematics', 'Física - Cinemática'), ('Physics_Waves', 'Física - Ondas'), ('Physics_Thermodynamics', 'Física - Termodinámica'), ('Physics_Electromagnetism', 'Física - Electromagnetismo'), ('Physics_Optics', 'Física - Óptica'), ('Physics_Mechanics', 'Física - Mecánica'), ('Physics_Acoustics', 'Física - Acústica'), ('Physics_Astronomy', 'Física - Astronomía'), ('Physics_Nuclear Physics', 'Física - Física Nuclear'), ('Physics_Relativity', 'Física - Relatividad'), ('Physics_Particle Physics', 'Física - Física de Partículas'), ('Physics_Dynamics', 'Física - Dinámica'), ('Physics_Energy', 'Física - Energía'), ('Technology', 'Tecnología y sociedad')], db_index=True, max_length=120),
        ),
    ]
