# Generated by Django 5.1.4 on 2025-01-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_create_question_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
