# Generated by Django 3.2.25 on 2024-05-31 00:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0002_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='date_taken',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='evaluation',
            name='student',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evaluations.course'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='name',
            field=models.CharField(default='Matemáticas', max_length=100),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='period',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='value_per_question',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Opciones de respuesta'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=100)),
                ('feedback', models.TextField(blank=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='evaluations.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
