# Generated by Django 5.1.4 on 2025-01-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_evaluation_llm_model_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
