# Generated by Django 5.1.4 on 2025-02-05 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0003_alter_question_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalPedagogicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_data', models.JSONField()),
                ('statistical_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['evaluation', 'is_latest'], name='evaluations_evaluat_59de85_idx')],
            },
        ),
    ]
