# Generated by Django 3.2.25 on 2024-05-31 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluations', '0004_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('evaluation', 'student')},
        ),
    ]
