# Generated by Django 3.2.25 on 2024-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_auto_20240531_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
