# Generated by Django 3.2.25 on 2024-06-01 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0007_alter_question_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=2),
        ),
    ]
