# Generated by Django 3.2.25 on 2024-06-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0009_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ManyToManyField(to='evaluations.Question'),
        ),
    ]
