# Generated by Django 3.2.25 on 2024-06-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0010_auto_20240601_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='selected_option',
        ),
        migrations.AddField(
            model_name='answer',
            name='selected_options',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Lista de respuestas'),
        ),
    ]
