# Generated by Django 3.2.25 on 2024-06-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0011_auto_20240602_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
