# Generated by Django 3.2.25 on 2024-06-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0012_alter_answer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='latex_format',
            field=models.BooleanField(default=False),
        ),
    ]
